language: csharp
sudo: required
dotnet: latest
services:
  - mysql
branches:
  only:
    - master
before_script:
  - sudo chmod -R 764 ./scripts
  - pwd
  - ls -a
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/dotnet-publish.sh