language: csharp
sudo: required
dotnet: 2.1.200
services:
  - mysql
branches:
  only:
    - master
before_script:
  - chmod -r a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/dotnet-publish.sh