version: "3"
services:
  web:
  image: "todolist:version1"
  ports:
  - "5000:5000"
  depends_on:
  - db
  db:
  image: "microsoft/mssql-server-linux:latest"
  environment:
  SA_PASSWORD: "Kleopatra2017@@"
ACCEPT_EULA: "Y"