version: "3"
services:
    web:
      container_name: api
      environment:
               ASPNETCORE_ENVIRONMENT: Production
      build: .
      depends_on:
          - db
      ports:
          - 8080:5001
      links: 
            - db
    db:
       container_name: db
       image: microsoft/mssql-server-linux
       ports :
              - 1434:1434
       environment:
           SA_PASSWORD: Kleopatra2017@@
           ACCEPT_EULA: Y