version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        ports :
          - "1434:1434"
        environment:
            SA_PASSWORD: "Kleopatra2017@@"
            ACCEPT_EULA: "Y"
    web:
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
        links: 
            - db
