version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports : "1434"
        environment:
            SA_PASSWORD: "Kleopatra2017@@"
            ACCEPT_EULA: "Y"